# NUMPY

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
print(a[0])
print(b[0])

1
[1 2 3 4]


### Array creation 

In [19]:
c=np.zeros(3)
d=np.ones(4)
e=np.empty(2)
f=np.arange(5)
g=np.arange(1,10,3)
h=np.linspace(0,12,num=3)  
i=np.ones(4,dtype=np.int64)



print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)

[0. 0. 0.]
[1. 1. 1. 1.]
[ 6. 12.]
[0 1 2 3 4]
[1 4 7]
[ 0.  6. 12.]
[1 1 1 1]
